<?php
#### Generated by Block Creator by Disipal Site (www.disipal.net) ###
if (eregi("block-Block_Creator.php",$PHP_SELF)) {
    Header("Location: index.php");
    die();
}
$content  =  "<center><EMBED type='application/x-mplayer2'";
$content  .= "        pluginspage='http://microsoft.com/windows/mediaplayer/en/download/'";
$content  .= "        id='MediaPlayer1' ";
$content  .= "		name='MediaPlayer1' ";
$content  .= "		displaysize='4' ";
$content  .= "		autosize='-1' ";
$content  .= "        bgcolor='darkblue' ";
$content  .= "		showcontrols=\"true\" ";
$content  .= "		showtracker='1' ";
$content  .= "        showdisplay='0' ";
$content  .= "		showstatusbar='1' ";
$content  .= "		videoborder3d='-1' ";
$content  .= "		width=\"320\" ";
$content  .= "		height=\"310\"";
$content  .= "        src=\"http://entimg.msn.com/i/asx/music_videos/Saliva_SurvivaloftheSickest.asx\" autostart=\"false\" designtimesp='5311' loop=\"false\">";
$content  .= "      </EMBED></center>";

?>