<?php
define("_ADDVID","Video hinzufügen");
define("_TITLE","Titel");
define("_POSTEDON","Geposted am");
define("_POSTEDBY","Geposted von");
define("_VVIEW","Ansehen");
define("_VIEWS","Views");
define("_PREVIOUS","Letzte Seite");
define("_NEXT","Nächste Seite");
define("_DESCRIPTION","Beschreibung");
define("_VIDURL","Video URL");
define("_PPURL","Bildvorschau URL");
define("_WIDTH","Breite");
define("_HEIGHT","Höhe");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Benötigte Felder");
define("_VIDADDPUBLICNOTE","Ihr Video wurde erfolgreich übermittelt. Ein Administrator wird es überprüfen, bevor es öffentlich gesehen werden kann.");
define("_VIDADDPUBLICNOTE2","Ihr Video wurde erfolgreich übertragen und der Sammlung hinzugefügt.");
define("_BROKENNOTICE","Danke für Ihren Hinweis, daß dieses Video nicht funktioniert. Der Administrator wurde benachrichtigt");
define("_BACK","zurück");
define("_VIDEOCOLECTION","Videosammlung");
define("_REPORTP1","Sie sind dabei, das Video");
define("_REPORTP2","als nicht funktionierend zu melden. Bitte hinterlassen Sie Ihren Benutzernamen und Ihre Email-Adresse. Der Administrator wird benachrichtigt. Vielen Dank!");
define("_USERNAME","Benutzername");
define("_EMAIL","Email");
define("_SUBMIT","Übertragen");
define("_TYCOMMENT","Danke für Ihren Kommentar");
define("_TYRATE","Danke für Ihre Bewertung");
define("_COMMENT","Kommentar");
define("_COMMENTS","Kommentare");
define("_SENDTOAFRIEND","An einen Freund schicken");
define("_BROKEN","Kaputt");
define("_SUBMITAVID","Video Übertragen");
define("_RATEVID","Bewerten Sie dieses Video");
define("_RATING","Bewertung");
define("_TVOTES","Gesamt Bewertungen");
define("_PAGE","Seite");
define("_NOVIDSINDB","Der Datenbank wurden noch keine Videos hinzugefügt");
define("_DOWNLOADVID","Haben Sie Probleme das Video anzusehen? Laden Sie es herunter");
define("_DOWNLOADFLASH","Haben Sie Probleme diese Flash Datei anzusehen? Laden Sie sie herunter");
define("_HERE","hier");
define("_NOCOMMENTS","keine Kommentare für dieses Video");
define("_NONE","Keine");
define("_CATEGORY","Kategorie");
define("_REGBROKEN","Es ist nur registrierten Mitgliedern erlaubt Videos als nicht funktionoerend zu melden");
define("_REGCOMMENT","Es ist nur registrierten Mitgliedern erlaubt einen Kommentar zu schreiben");
define("_REGSUBMIT","Es ist nur registrierten Mitgliedern erlaubt Videos zu übertragen");
define("_REGRATE","Es ist nur registrierten Mitgliedern erlaubt Videos zu bewerten");
define("_REGSEND","Es ist nur registrierten Mitgliedern erlaubt Videos an einen Freund zu senden");
define("_REGWATCH","Es ist nur registrierten Mitgliedern erlaubt Videos anzusehen");
define("_VIDEOCOLECTION","Videosammlung");
define("_YOURFRIEND","Ihr Freund");
define("_HASRECOMMEND","hat empfohlen, daß Sie sich dieses Video ansehen");
define("_EMAILSENT","Email versendet an");
define("_EMAILNOTSENT","Beim senden Ihrer Email ist ein Fehler aufgetreten");
define("_YNAME","Ihr Name");
define("_YEMAIL","Ihre Email-Adresse");
define("_FNAME","Name Ihres Freundes");
define("_FEMAIL","Email-Adresse Ihres Freundes");
define("_SEND","Senden");
// NEW TO V4.1 
define("_SORT","Sortieren"); 
define("_SEARCH","Suchen"); 
define("_SEARCHVIDS","Videos Suchen"); 
define("_SORTANDSEARCH","Sortieren & Videos Suchen"); 
define("_ORDERVIDS","Ordne Videos Nach"); 
define("_DISPLAYCATEGORY","Nach Kategorie Anzeigen"); 
define("_ALL","Alle"); 
define("_NEWEST","Neuestes"); 
define("_OLDEST","Ältestes"); 
define("_HIGHESTR","Höchst Bewertetes"); 
define("_MOSTVIEW","Meist Gesehenes"); 
define("_EMBEDVIDURL","Video URL oder &lt;embed&gt; code"); 
define("_CUSTOMEMBED","Eigener &lt;embed&gt; Code"); 
define("_NOMATCHES","Es wurden keine Ergebnisse gefunden");
// NEW to V4.2
define("_VS_COMMENT","Kommentar"); // DLETE define("_COMMENT","Comment"); above
define("_VS_COMMENTS","Kommentare"); // DLETE define("_COMMENTS","Comments"); above
define("_NOTALLFIELDSFILLED","Nicht alle erforderlichen Felder wurden ausgefüllt. Bitte zurückgehen und noch einmal versuchen");
define("_NOTALLFIELDSFILLEDCORRECTLY","Nicht alle Felder wurden korrekt ausgefüllt. Bitte zurückgehen und noch einmal versuchen");
define("_PICTURETHUMB","Miniaturbild");
define("_NOCOMMENTENT","Kein Kommentar eingegeben");
define("_COMMENTMODED","Das Kommentar wurde geändert");
define("_ERROR","Fehler");
define("_JOINON","Mitglied seit");
define("_BACKTOTOP","Nach oben");
define("_SENDPMESS","Private Nachricht versenden");
define("_VISITPOSTWEB","Die Webseite des Benutzers besuchen");
define("_SENDEMAIL","E-mail versenden");
define("_AIMADDRESS","AIM Adresse");
define("_YIMADDRESS","YIM Adresse");
define("_MSNMESSENGERADD","MSN Messenger");
define("_ICQNUMBER","ICQ Nummer");
define("_AREUSURE","Sind Sie sich sicher?");
define("_EDITCOMM","Kommentar barbeiten");
define("_DELETECOMM","Kommentar löschen");
define("_BACKTOVIDS","Zurück zu den Videos");
define("_STATISTICS","Statistiken");
define("_WECURRENTHAVE","Wir haben zur Zeit");
define("_VS_VIDEOS","Videos");
define("_WITHALLVIDSHAD","Bisher waren es insgesamt");
define("_VS_VIEWS","Ansichten");
define("_ONAVERAGE","Im Durchschnitt sind das");
define("_VIEWSPERVID","Ansichten pro Video");
define("_COMMSPERVID","Kommentare pro Video");
define("_INTOTALHAVE","Insgesamt haben wir");
define("_VS_COMMS","Kommentare");
define("_ALLTOGETHERHAD","Insgesamt haben diese");
define("_VS_RATES","Bewertung");
define("_AVERAGERATEPV","Die durschnittliche Bewertung pro Video ist");
define("_MOREFROMUSER","Mehr von diesem Benutzer");
define("_PLAYINPOPUP","Video in einem PopUp Fenster abspielen");
define("_MOREVIDS","Mehr Videos");
define("_HELPFORSEARCH","Suchmethode:<br>title:string (Suche nach Titeln)<br>description:string (Suche nach Beschreibung)<br>user:string (Suche nach Benutzer)");

?>