<?php
define("_ADDVID","Video toevoegen");
define("_TITLE","Tite;");
define("_POSTEDON","gepost op");
define("_POSTEDBY","gepost door");
define("_VVIEW","View");
define("_VIEWS","Views");
define("_PREVIOUS","Vorige pagina");
define("_NEXT","Volgende pagina");
define("_DESCRIPTION","Beschrijving");
define("_VIDURL","Video URL");
define("_PPURL","Picture Preview URL");
define("_WIDTH","Breedte");
define("_HEIGHT","Hoogte");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Benodigde velden");
define("_VIDADDPUBLICNOTE","Je video is met succes toegevoegd maar een admin controleert hem eerst");
define("_VIDADDPUBLICNOTE2","Je video is met succes toegevoegd bij onze collectie");
define("_BROKENNOTICE","Bedankt, de admin is nu op de hoogte");
define("_BACK","Terug");
define("_VIDEOCOLECTION","Video Collectie");
define("_REPORTP1","Je staat op het punt om te melden");
define("_REPORTP2","Als niet werkende.Laat je gebruikersnaam en e-mail adres achter de admin weet dan meer.bedankt!");
define("_USERNAME","Gebruikersnaam");
define("_EMAIL","Email");
define("_SUBMIT","Toevoegen");
define("_TYCOMMENT","Bedankt voor je commentaar");
define("_TYRATE","Bedankt voor je rating");
define("_COMMENT","Commentaar");
define("_COMMENTS","Commentaar");
define("_SENDTOAFRIEND","naar een vriend verzendem");
define("_BROKEN","Doet het niet");
define("_SUBMITAVID","Video toevoegen");
define("_RATEVID","video raten");
define("_RATING","Rating");
define("_TVOTES","Totaal aantal stemmen");
define("_PAGE","Pagina");
define("_NOVIDSINDB","Er zijn nog geen videos in de database");
define("_DOWNLOADVID","Problemen met deze video bekijken? download het");
define("_DOWNLOADFLASH","Problemen met deze flash file bekijken? Download het");
define("_HERE","hier");
define("_NOCOMMENTS","geen commentaar bij deze video");
define("_NONE","geen");
define("_CATEGORY","Categorie");
define("_REGBROKEN","Alleen geregristreerde gebruikers zijn toegestaan om videos als fout te melden");
define("_REGCOMMENT","Alleen geregristreerde gebruikers zijn toegestaan om commentaar te geven");
define("_REGSUBMIT","Alleen geregristreerde gebruikers zijn toegestaan om videos toe te voegen");
define("_REGRATE","Alleen geregristreerde gebruikers zijn toegestaan om videos te raten");
define("_REGSEND","Alleen geregristreerde gebruikers zijn toegestaan om videos naar een vriend te zenden");
define("_REGWATCH","Alleen geregristreerde gebruikers zijn toegestaan om videos te bekijken");
define("_VIDEOCOLECTION","Video Collectie");
define("_YOURFRIEND","Je vriend");
define("_HASRECOMMEND","Raad jou aan om deze video te bekijken");
define("_EMAILSENT","Email zenden naar");
define("_EMAILNOTSENT","Er is een fout opgetreden tijdens het zenden van je mail");
define("_YNAME","Je naam");
define("_YEMAIL","je Email");
define("_FNAME","Naam vriend");
define("_FEMAIL","vriend's Email");
define("_SEND","Sturen");
// NEW TO V4.1 
define("_SORT","Sorteren"); 
define("_SEARCH","Zoeken"); 
define("_SEARCHVIDS","Videos zoeken"); 
define("_SORTANDSEARCH","Videos zoeken & sorteren"); 
define("_ORDERVIDS","Videos sorteren met"); 
define("_DISPLAYCATEGORY","Tonen per categorie"); 
define("_ALL","Allemaal"); 
define("_NEWEST","Nieuwste"); 
define("_OLDEST","Oudste"); 
define("_HIGHESTR","Hoogst gerated"); 
define("_MOSTVIEW","Meest bekeken"); 
define("_EMBEDVIDURL","Video URL or &lt;embed&gt; code"); 
define("_CUSTOMEMBED","Custom &lt;embed&gt; Code"); 
define("_NOMATCHES","er zijn geen resultaten gevonden sorry");
?>