<?php
define("_ADDVID","Ajouter une Vidéo");
define("_TITLE","Titre");
define("_POSTEDON","Posté le");
define("_POSTEDBY","Posté par");
define("_VVIEW","Vue");
define("_VIEWS","Vues");
define("_PREVIOUS","Page Précédente");
define("_NEXT","Page Suivante");
define("_DESCRIPTION","Description");
define("_VIDURL","URL de la Vidéo");
define("_PPURL","URL de la prévisualition de l'image vidéo");
define("_WIDTH","Largeur");
define("_HEIGHT","Hauteur");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Besoin de champs");
define("_VIDADDPUBLICNOTE","Votre vidéo a été soumise avec succès et un admin la vérifiera avant que la vidéo puisse être regardée en public .");
define("_VIDADDPUBLICNOTE2","Votre vidéo a été soumise avec succès et a été ajoutée à notre collection .");
define("_BROKENNOTICE","Merci d'avoir effectué un rapport sur cette vidéo qui ne fonctionne pas. l'administrateur sera prévenu.");
define("_BACK","Retour");
define("_VIDEOCOLECTION","Collection Vidéo");
define("_REPORTP1","Vous êtes sur le point d'effectuer un rapport sur");
define("_REPORTP2","car cela ne fonctionne pas, veuillez laisser votre pseudo et votre email ci-dessous ainsi l'admin sera prévenu . Merci ");
define("_USERNAME","Pseudo");
define("_EMAIL","Email");
define("_SUBMIT","Soumettre");
define("_TYCOMMENT","Merci pour votre commentaire");
define("_TYRATE","Merci pour votre vote");
define("_COMMENT","Ajouter un Commentaire");
define("_COMMENTS","Commentaires");
define("_SENDTOAFRIEND","Envoyer à un ami");
define("_BROKEN","Avertir du lien vidéo cassé");
define("_SUBMITAVID","Soumettre une vidéo");
define("_RATEVID","Voter pour cette vidéo");
define("_RATING","Classement");
define("_TVOTES","Total des Votes");
define("_PAGE","Page");
define("_NOVIDSINDB","Aucune vidéo n'a encore été entré dans la base de données");
define("_DOWNLOADVID","Avez-vous des problemes pour visionner cette vidéo? Sinon téléchargez");
define("_DOWNLOADFLASH","Avez-vous des problemes pour visionner ce fichier Flash? Sinon téléchargez");
define("_HERE","ici");
define("_NOCOMMENTS","Pas de commentaires pour cette vidéo");
define("_NONE","Aucune");
define("_CATEGORY","Catégorie");
define("_REGBROKEN","Seulement les membres enregistrés sont autorisés à rapporter des vidéos comme cassés ");
define("_REGCOMMENT","Seulement les membres enregistrés sont autorisés à commenter");
define("_REGSUBMIT","Seulement les membres enregistrés sont autorisés à soumettre des vidéos");
define("_REGRATE","Seulement les membres enregistrés sont autorisés à voter pour les vidéos");
define("_REGSEND","Seulement les membres enregistrés sont autorisés à envoyer des vidéos à un ami");
define("_REGWATCH","Seulement les membres enregistrés sont autorisés à regarder les vidéos");
define("_VIDEOCOLECTION","Video Collection");
define("_YOURFRIEND","Votre ami");
define("_HASRECOMMEND","Vous recommande cette vidéo");
define("_EMAILSENT","Email envoyé à");
define("_EMAILNOTSENT","Il y a eu une erreur en envoyant votre email");
define("_YNAME","Votre nom");
define("_YEMAIL","Votre Email");
define("_FNAME","Nom de votre ami");
define("_FEMAIL","Email de votre ami");
define("_SEND","Envoyer");
// NEW TO V4.1
define("_SORT","Type");
define("_SEARCH","Rechercher");
define("_SEARCHVIDS","Recherche de vidéos");
define("_SORTANDSEARCH","Type & Recherche de vidéos");
define("_ORDERVIDS","Classer les vidéos");
define("_DISPLAYCATEGORY","Affichage par catégorie");
define("_ALL","Toutes");
define("_NEWEST","Plus récentes");
define("_OLDEST","Plus anciennes");
define("_HIGHESTR","Meilleurs votes");
define("_MOSTVIEW","Plus regardées");
define("_EMBEDVIDURL","URL de la vidéo ou code &lt;embed&gt;");
define("_CUSTOMEMBED","Personnaliser Code &lt;embed&gt;");
define("_NOMATCHES","désolé aucun résultat de recherche n'a été trouvé ");
?>
