<?php
define("_ADDVID","Añadir Video");
define("_TITLE","Titulo");
define("_POSTEDON","Enviado el");
define("_POSTEDBY","Enviado por");
define("_VVIEW","Ver");
define("_VIEWS","Visto");
define("_PREVIOUS","Página Anterior");
define("_NEXT","Página Siguiente");
define("_DESCRIPTION","Descripción");
define("_VIDURL","URL del vídeo");
define("_PPURL","URL de la imagen para vista previa");
define("_WIDTH","Ancho");
define("_HEIGHT","Largo");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Campos requeridos");
define("_VIDADDPUBLICNOTE","Tu vídeo ha sido enviado correctamente un administrador lo revisará antes de que lo vea el publico. GRACIAS");
define("_VIDADDPUBLICNOTE2","Tu vídeo ha sido enviado correctamente y ha sido añadido sin problemas.");
define("_BROKENNOTICE","Gracias por informar de que este vídeo esta roto. Un administrador lo revisará.");
define("_BACK","Atrás");
define("_VIDEOCOLECTION","Colección de vídeos");
define("_REPORTP1","Vas a Informar");
define("_REPORTP2","como que no funciona porfavor rellena  los huecos con tu nombre y e-mail. El administrador sera informado. Gracias!");
define("_USERNAME","Uusuario");
define("_EMAIL","Email");
define("_SUBMIT","Enviar");
define("_TYCOMMENT","Gracias por tu comentario");
define("_TYRATE","Gracias por Valorar el vídeo");
define("_COMMENT","Comentar");
define("_COMMENTS","Comentarios");
define("_SENDTOAFRIEND","Enviar a un amigo");
define("_BROKEN","Roto");
define("_SUBMITAVID","Enviar vídeo");
define("_RATEVID","Valorar este vídeo");
define("_RATING","Puntuaci&oacute;n");
define("_TVOTES","Votos totales");
define("_PAGE","Pagina");
define("_NOVIDSINDB","Todavia no hay vídeos en nuestra base de datos");
define("_DOWNLOADVID","¿Tienes problemas para ver este vídeo?. Descargatelo");
define("_DOWNLOADFLASH","¿Tienes problemas para ver este flash?. Descargatelo");
define("_HERE","Aquí");
define("_NOCOMMENTS","No hay comentarios para este vídeo");
define("_NONE","Nada");
define("_CATEGORY","Categoria");
define("_REGBROKEN","Sólo los usuarios registrados pueden avisar de que el vídeo esta roto");
define("_REGCOMMENT","Sólo los usuarios registrados pueden comentar");
define("_REGSUBMIT","Sólo los usuarios registrados pueden enviar vídeos");
define("_REGRATE","Sólo los usuarios registrados pueden valorar/");
define("_REGSEND","Sólo los usuarios registrados pueden enviar vídeos");
define("_REGWATCH","Sólo los usuarios registrados pueden ver los vídeos");
define("_VIDEOCOLECTION","Colleción de vídeos");
define("_YOURFRIEND","Tu amigo");
define("_HASRECOMMEND","te han recomendado este vídeo");
define("_EMAILSENT","Email enviado a");
define("_EMAILNOTSENT","Hubo un error enviado tu mail");
define("_YNAME","Tu nombre");
define("_YEMAIL","Tu E-mail");
define("_FNAME","Nombre de tu amigo");
define("_FEMAIL","E-mail de tu amigo");
define("_SEND","Enviar");
// NEW TO V4.1
define("_SORT","Mostar");
define("_SEARCH","Buscar");
define("_SEARCHVIDS","Buscar V&iacute;deos");
define("_SORTANDSEARCH","Mostar & Buscar vídeos");
define("_ORDERVIDS","Ordenar v&iacute;deos Por");
define("_DISPLAYCATEGORY","Mostrar por categorias");
define("_ALL","Todos");
define("_NEWEST","Nuevos");
define("_OLDEST","Viejos");
define("_HIGHESTR","Highest Rated");
define("_MOSTVIEW","Mas vistos");
define("_EMBEDVIDURL","vídeo URL o &lt;embed&gt; codigo");
define("_CUSTOMEMBED","Custom &lt;embed&gt; Codigo");
define("_NOMATCHES","Lo siento pero no hay resultados para su busqueda");
// NEW to V4.2
define("_VS_COMMENT","Comentario"); // DLETE define("_COMMENT","Comment"); above
define("_VS_COMMENTS","Comentarios"); // DLETE define("_COMMENTS","Comments"); above
define("_NOTALLFIELDSFILLED","No has rellenado todos los campos porfavor rellenelos.");
define("_NOTALLFIELDSFILLEDCORRECTLY","No se han rellenado todos los campos correctamente, porfavor reviselos.");
define("_PICTURETHUMB","Foto para Thumbnail");
define("_NOCOMMENTENT","No hay comentarios");
define("_COMMENTMODED","El comentario ha sido modificado");
define("_ERROR","Error");
define("_JOINON","En la web desde");
define("_BACKTOTOP","Subir arriba");
define("_SENDPMESS","Enviar mensaje privado");
define("_VISITPOSTWEB","Visitar su web");
define("_SENDEMAIL","Enviar e-mail");
define("_AIMADDRESS","Dirección AIM");
define("_YIMADDRESS","Dirección YIM");
define("_MSNMESSENGERADD","MSN Messenger");
define("_ICQNUMBER","Número ICQ");
define("_AREUSURE","¿Esta seguro?");
define("_EDITCOMM","Editar comentario");
define("_DELETECOMM","Borrar comentario");
define("_BACKTOVIDS","Volver a vídeos");
define("_STATISTICS","Estadísticas");
define("_WECURRENTHAVE","Actualmente tenemos");
define("_VS_VIDEOS","v&iacute;deos");
define("_WITHALLVIDSHAD","con todos estos vídeos hemos tenido");
define("_VS_VIEWS","visitas");
define("_ONAVERAGE","Con una media de");
define("_VIEWSPERVID","visiones por v&iacute;deo");
define("_COMMSPERVID","comentarios por v&iacute;deo");
define("_INTOTALHAVE","En total tenemos");
define("_VS_COMMS","comentarios");
define("_ALLTOGETHERHAD","Todo junto hace que tengamos");
define("_VS_RATES","valoraciones");
define("_AVERAGERATEPV","La media de valoraciones es");
define("_MOREFROMUSER","M&aacute;s sobre este usuario");
define("_PLAYINPOPUP","Reproducir v&iacute;deo en una nueva ventana");
define("_MOREVIDS","M&aacute;s V&iacute;deos ");
define("_HELPFORSEARCH","M&eacute;todos de busquedas:<br>t&iacute;tulo:string (Buscar por t&iacute;tulo)<br>descripción:string (Buscar vídeos por descripción)<br>usuario:string (Buscar vídeos por usuario)");
define("_VS_INFO", "Informaci&oacute;n");
define("_REPORTASBROKEN", "Reportar este v&iacute;deo como roto");
define("_RATINGSANDREVIEWS", "Puntuaciones y Votos");
define("_RATE", "Votar"); // DELETE define("_RATEVID","Rate this video"); above
define("_ADDCOMMENTTOVID", "Agregar un comentario para este video");
define("_TELLEVERYBOUTVID", "Avisa a todos sobre este v&iacute;deo");
define("_HTMLLINK", "Link HTML");
define("_BBLINK", "Link BB");
define("_EMAILLINK", "Link Email");
define("_DOWNLOAD", "Descargar");
define("_DOWNLOADVID", "Descargar Video"); // DELETE define("_DOWNLOADVID","Are you having trouble veiwing this video? Download it"); above
// NEW to 4.5
define("_VS_ACCEPT", "Aceptar");
define("_VS_REJECT", "Rechazar");
define("_YOUTUBEVP", "YouTube Player");
define("_GOOGLEVP", "Google Video Player");
define("_ALPHABETICALLY", "Alfabeticamente");
define("_EMBEDEDHTML", "HTML Embebido");
?>