<?php
define("_ADDVID","Videó Hozzáadása");
define("_TITLE","Cím");
define("_POSTEDON","Beküldve");
define("_POSTEDBY","Beküldte");
define("_VVIEW","Megnéz?");
define("_VIEWS","Megnézve");
define("_PREVIOUS","Elõzõ oldal");
define("_NEXT","Következõ oldal");
define("_DESCRIPTION","Leírás");
define("_VIDURL","Videó URL");
define("_PPURL","Elõnézeti Kép URL");
define("_WIDTH","Szélesség");
define("_HEIGHT","Magasság");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Kötelezõ Mezõk (Kitölteni)");
define("_VIDADDPUBLICNOTE","A Videó sikeresen hozzáadva, egy adminisztrátor ellenõrzi majd, mieéõtt nyilvános lesz.");
define("_VIDADDPUBLICNOTE2","A Videó sikeresen hozzáadva a Kollekcióhoz.");
define("_BROKENNOTICE","Köszönjük a hiba jelentését! Az adminisztrátor értesítve.");
define("_BACK","vissza");
define("_VIDEOCOLECTION","Videó Kollekció");
define("_REPORTP1","A");
define("_REPORTP2","videót készülsz hibásnak jelenteni. Kérünk, add meg felhasználói neved és email címed, és az adminisztrátor értesítve lesz. Köszönjük!");
define("_USERNAME","Felhasználónév");
define("_EMAIL","Email");
define("_SUBMIT","Mehet");
define("_TYCOMMENT","Köszönjük a hozzászólást");
define("_TYRATE","Köszönjük az értékelést!");
define("_COMMENT","Hozzászólás");
define("_COMMENTS","Hozzászólások");
define("_SENDTOAFRIEND","Küldés egy ismerõsnek");
define("_BROKEN","Hibásnak jelölés");
define("_SUBMITAVID","Videó beküldése");
define("_RATEVID","Videó osztályzása");
define("_RATING","Osztályzat");
define("_TVOTES","Összes szavazat");
define("_PAGE","Oldal");
define("_NOVIDSINDB","Nem adtál még videót az adatbázishoz.");
define("_DOWNLOADVID","Problémád van a videó lejátszásával? Tölcsd le!");
define("_DOWNLOADFLASH","Problémád van a Flash fájl megnézésével? Tölcsd le!");
define("_HERE","itt");
define("_NOCOMMENTS","Nincs hozzászólás a videóhoz");
define("_NONE","Nincs");
define("_CATEGORY","Kategória");
define("_REGBROKEN","Csak Regisztrált Felhasználók tudnak videó hibajelentlst küldeni");
define("_REGCOMMENT","Csak Regisztrált Felhasználók tudnak hozzászólni a videókhoz to comment");
define("_REGSUBMIT","Csak Regisztrált Felhasználók tudnak videót beküldeni");
define("_REGRATE","Csak Regisztrált Felhasználók tudnak videót osztályozni");
define("_REGSEND","Csak Regisztrált Felhasználók tudnak videót ismerõsnek ajánlani");
define("_REGWATCH","Csak Regisztrált Felhasználók tudnak videót lejátszani");
define("_VIDEOCOLECTION","Videó Kollekció");
define("_YOURFRIEND","Ismerõsöd");
define("_HASRECOMMEND","ajánlotta,hogy nézd meg ezt a videót");
define("_EMAILSENT","Email elküldve ide");
define("_EMAILNOTSENT","Hiba történt az email elküldésekor");
define("_YNAME","Neved");
define("_YEMAIL","Email címed");
define("_FNAME","Ismerõsöd Neve");
define("_FEMAIL","Ismerõsöd Email címe");
define("_SEND","Küldés");
// NEW TO V4.1
define("_SORT","Rendez");
define("_SEARCH","Keresés");
define("_SEARCHVIDS","Videók Keresése");
define("_SORTANDSEARCH","Videók Rendezése és Keresése");
define("_ORDERVIDS","Videók Rendezése");
define("_DISPLAYCATEGORY","Kategória megjelenítése");
define("_ALL","Mindet");
define("_NEWEST","Újabbak elõre");
define("_OLDEST","Régebbiek elõre");
define("_HIGHESTR","Osztályzat szerint");
define("_MOSTVIEW","Nézettebb elõre");
define("_EMBEDVIDURL","Videó URL vagy &lt;embed&gt; code");
define("_CUSTOMEMBED","Egyéni &lt;embed&gt; Code");
define("_NOMATCHES","Sajnos a keresés eredménytelen");
?>