<?php
define("_ADDVID","Dodaj video");
define("_TITLE","Naziv");
define("_POSTEDON","Postavljeno");
define("_POSTEDBY","Postavio");
define("_VVIEW","Pogledaj");
define("_VIEWS","Pregleda");
define("_PREVIOUS","Prethodna strana");
define("_NEXT","Sljedeæa strana");
define("_DESCRIPTION","Opis videa");
define("_VIDURL","Lokacija videa");
define("_PPURL","Slika iz videa");
define("_WIDTH","Širina");
define("_HEIGHT","Visina");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Obavezna polja");
define("_VIDADDPUBLICNOTE","Vaš je video fajl dodan. Potrebno je da ga administrator pogleda i odobri.");
define("_VIDADDPUBLICNOTE2","Vaš je video uspješno dodan u našu video galeriju.");
define("_BROKENNOTICE","Hvala za obavijest da postoji problem sa ovim video fajlom. Administrator æe to riješiti èim prije.");
define("_BACK","nazad");
define("_VIDEOCOLECTION","Video kolekcija");
define("_REPORTP1","Želite prijaviti da postoji problem");
define("_REPORTP2",". Ostavite nam Vaše ime i e-mail adresu kako biste Administratora obavijestili o promjenama!");
define("_USERNAME","Korisnik");
define("_EMAIL","E-mail");
define("_SUBMIT","Pošalji");
define("_TYCOMMENT","Hvala za komentar.");
define("_TYRATE","Hvala za glas");
define("_SENDTOAFRIEND","Pošalji prijatelju");
define("_BROKEN","Kvar");
define("_SUBMITAVID","Postavi Video");
define("_RATING","Ocjena");
define("_TVOTES","Ukupno glasova");
define("_PAGE","Strana");
define("_NOVIDSINDB","U bazi još uvijek nema video fajlova");
define("_DOWNLOADFLASH","Imate li problema sa pregledom ovog flash fajla? Downloadajte ga");
define("_HERE","ovdje");
define("_NOCOMMENTS","Nema komentara za ovaj video fajl");
define("_NONE","Nijedan/na");
define("_CATEGORY","<b>Kategorija<b>");
define("_REGBROKEN","Samo registrovanima je omoguæeno prijavljivanja kvara");
define("_REGCOMMENT","Samo registrovanima je omoguæeno komentiranje");
define("_REGSUBMIT","Samo registrovanima je omoguæeno da postave video fajl");
define("_REGRATE","Samo registrovanima je omoguæeno da ocjenjuju video fajlove");
define("_REGSEND","Samo registrovanima je omoguæeno da pošalju video prijateljima");
define("_REGWATCH","Samo registrovanima je omoguæeno da pogledaju ovaj video fajl");
define("_VIDEOCOLECTION","Video kolekcija");
define("_YOURFRIEND","Vaš prijatelj");
define("_HASRECOMMEND","želi da pogledate ovaj video");
define("_EMAILSENT","E-mail poslan");
define("_EMAILNOTSENT","Nastao je problem u slanju vašeg e-maila");
define("_YNAME","Vaše ime");
define("_YEMAIL","Vaš e-mail");
define("_FNAME","Prijateljevo ime");
define("_FEMAIL","Prijateljev e-mail");
define("_SEND","Pošalji");
// NOVO U VERZIJI V4.1
define("_SORT","Sortiraj");
define("_SEARCH","Pretraži");
define("_SEARCHVIDS","Potraži video");
define("_SORTANDSEARCH","Sortiranje i traženje videa");
define("_ORDERVIDS","Poredaj video fajlove po");
define("_DISPLAYCATEGORY","Prikaži po kategoriji");
define("_ALL","Svi");
define("_NEWEST","Najnoviji");
define("_OLDEST","Najstariji");
define("_HIGHESTR","Najbolje ocjenjeni");
define("_MOSTVIEW","Najgledaniji");
define("_EMBEDVIDURL","Lokacija videa ili code");
define("_CUSTOMEMBED","Uredi code");
define("_NOMATCHES","Nije pronaðen nijedan video fajl");
// NOVO U VERZIJI V4.2
define("_VS_COMMENT","Komentar"); // Izbriši define("_COMMENT","Komentar"); iznad
define("_VS_COMMENTS","Komentari"); // Izbriši define("_COMMENTS","Komentara"); iznad
define("_NOTALLFIELDSFILLED","Nisu ispunjena sva potrebna polja. Vratite se nazad i ispunite ih.");
define("_NOTALLFIELDSFILLEDCORRECTLY","Nisu ispunjena sva potrebna polja na valjan naèin. Vratite se nazad i ispunite ih ponovno");
define("_PICTURETHUMB","Umanjeni prikaz");
define("_NOCOMMENTENT","Nema unesenih komentara");
define("_COMMENTMODED","Komentar je modificiran");
define("_ERROR","GREŠKA!");
define("_JOINON","Pridružen");
define("_BACKTOTOP","Nazad na vrh");
define("_SENDPMESS","Pošalji privatnu poruku");
define("_VISITPOSTWEB","Posjeti web-site autora");
define("_SENDEMAIL","Pošalji e-mail");
define("_AIMADDRESS","AIM Addresa");
define("_YIMADDRESS","YIM Addresa");
define("_MSNMESSENGERADD","MSN Messenger");
define("_ICQNUMBER","ICQ broj");
define("_AREUSURE","Jeste li sigurni?");
define("_EDITCOMM","Uredi komentar");
define("_DELETECOMM","Izbriši komentar");
define("_BACKTOVIDS","Nazad na video fajlove");
define("_STATISTICS","Statistika");
define("_WECURRENTHAVE","Trenutno imamo");
define("_VS_VIDEOS","video fajlova");
define("_WITHALLVIDSHAD","Imali smo ukupno");
define("_VS_VIEWS","pregleda");
define("_ONAVERAGE","To je u prosjeku");
define("_VIEWSPERVID","pregleda po fajlu");
define("_COMMSPERVID","komentara po fajlu");
define("_INTOTALHAVE","Ukupno imamo");
define("_VS_COMMS","komentara");
define("_ALLTOGETHERHAD","Ukupno je");
define("_VS_RATES","puta glasano");
define("_AVERAGERATEPV","Prosjeèna ocjena po video fajlu je");
define("_MOREFROMUSER","Više od ovog korisnika");
define("_PLAYINPOPUP","Pogledaj video u novom prozoru");
define("_MOREVIDS","Više video fajlova");
define("_HELPFORSEARCH","Metode pretrage:<br>(Po nazivu)<br>(Po opisu)<br>(Po pošiljatleju video fajla)");
define("_VS_INFO", "Info");
define("_REPORTASBROKEN", "Prijavi ovaj video kao pokvaren");
define("_RATINGSANDREVIEWS", "Ocjene i komentari");
define("_RATE", "Glasaj"); // Izbriši define("_RATEVID","Ocijeni ovaj video"); iznad
define("_ADDCOMMENTTOVID", "Dodaj komentar na ovaj video fajl");
define("_TELLEVERYBOUTVID", "Reci prijateljima o ovom video fajlu");
define("_HTMLLINK", "HTML Link");
define("_BBLINK", "BB Link");
define("_EMAILLINK", "E-mail Link");
define("_DOWNLOAD", "Download");
define("_DOWNLOADVID", "Download videa"); // Izbriši define("_DOWNLOADVID","Imate li problema sa pregledom ovog fajla? Preuzmite ga!"); iznad
?>