<?php
// *************************************************
// This file is Part of Nuke_Reflections V1 Module by
// White_Devil of http://devil-modz.us
// E-Mail arleighesq@gmail.com

// Please do not remove any copyright notices
// Or modify beyond the main parts of this script

// Everything is pretty much Explained.
// *************************************************

//************************************************************
// DO NOT EDIT THIS FILE!!!!
//************************************************************
require_once("mainfile.php");
$module_name = basename(dirname(__FILE__));
require_once("modules/$module_name/includes/devil_includes.php");



$row = $db->sql_fetchrow($db->sql_query("SELECT * FROM " . $prefix . "_reflections_config WHERE configinfo='configsys'"));



$commentsecurity = $row['commentsecurity'];
$membersecuritycreate = $row['membersecuritycreate'];
$membersecurityupload = $row['membersecurityupload'];
$guestvote = $row['guestvote'];
$allowguestcomment = $row['allowguestcomment'];


$allowmemberupload = $row['allowmemberupload'];
$allowmembergalleries = $row['allowmembergalleries'];
$allowmembermulti = $row['allowmembermulti'];
$membermultilimit = $row['membermultilimit'];
$requireapproval = $row['requireapproval'];
$memberlimit = $row['memberlimit'];
$membermaxsize = $row['membermaxsize'];
$allowmemberdelcomment = $row['allowmemberdelcomment'];

//done below
$loginkilltime = $row['loginkilltime'];
$maxperpage = $row['maxperpage'];
$maxthumbsizegal = $row['maxthumbsizegal'];
$config_thumbsize = $row['config_thumbsize'];
$watermark = $row['watermark'];
$watermark_text1 = $row['watermark_text1'];
$watermark_text1 = devilcleanitupfix($watermark_text1);
$watermark_text2 = $row['watermark_text2'];
$watermark_text2 = devilcleanitupfix($watermark_text2);
$watermarkimage = $row['watermarkimage'];
$tooltippic = $row['tooltippic'];
$tooltipback = $row['tooltipback'];
$NRVersion = $row['version'];
$tooltiptext = $row['tooltiptext'];
$tooltipbordercolor = $row['tooltipbordercolor'];
$voterestriction = $row['voterestriction'];
$killfilereportedonmax = $row['killfilereportedonmax'];
$filereportmax = $row['filereportmax'];
$SoNTransferallow = $row['SoNTransferallow'];
$showbbcodesystem = $row['allowbbcode'];
if ($SoNTransferallow == "") {
	$SoNTransferallow = "0";
}

//autofolderdetection
$modulefolderlocation = $row['modulefolderNR'];
if ($modulefolderlocation != $module_name) {
$db->sql_query("update " . $user_prefix . "_reflections_config set modulefolderNR='$module_name' where configinfo='configsys'");
}




?>