<?php
define("_ADMINMENU","Administration");
define("_VIDEOADMIN","Video Admin");
define("_MANAGEVIDS","Videos Verwalten");
define("_ADDVIDS","Videos Hinzufügen");
define("_ADDVID","Video Hinzufügen");
define("_EDITVID","Video Bearbeiten");
define("_VIDADDED","Video Hinzugefügt");
define("_SETTINGSVIDS","Video Stream Einstellungen");
define("_TITLE","Titel");
define("_POSTEDON","Gepostet am");
define("_POSTEDBY","Grpostet von");
define("_VVIEW","Ansehen");
define("_VIEWS","Views");
define("_EDIT","Bearbeiten");
define("_DELETE","Löschen");
define("_DELETEVID","Video Löschen");
define("_PREVIOUS","Vorheriges");
define("_NEXT","Nächstes");
define("_NOVIDSINDB","Sie haben der Datanbank noch keine Videos hinzugefügt.");
define("_DESCRIPTION","Beschreibung");
define("_VIDURL","Video URL");
define("_PPURL","Bildvorschau URL");
define("_WIDTH","Breite");
define("_HEIGHT","Höhe");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Benötigte Felder");
define("_PAGE","Seite");
define("_DELETEVIDCOMFIRM","Sie sind dabei dieses Video zu löschen. Sind Sie sicher?");
define("_YES","Ja");
define("_NO","Nein");
define("_VIDDELETED","Video gelöscht");
define("_BACK","zurück");
define("_NONE","keins");
define("_CATEGORY","Kategorie");
define("_ENTDELETED","Eintrag gelöscht");
define("_ENTRYCOMFIRM","Sie sind dabei alle Einträge für dieses Video zu löschen. Sind Sie icher?");
define("_REPORTEDBROKE","Als nicht funktionierend gemeldete Videos");
define("_VIDNAME","Videoname");
define("_USERNAME","Benutzername");
define("_EMAIL","Email Adresse");
define("_DELETEENT","Alle Einträge für dieses Video löschen");
define("_GO","Los");
define("_GOBACKVID","Zurück zur Video Stream Hauptadministrations-Seite?");
define("_NOBROKEN","Keine Videos wurden als nicht funktionierend gemeldet");
define("_ENABLE","Aktivieren");
define("_DISABLE","Deaktivieren");
define("_EVERYONE","Jeden");
define("_NOONE","Niemand");
define("_VISONLY","Nur für Besucher");
define("_REGMEMBERSONLY","Nur für registrierte Mirglieder");
define("_COMMENTPOSTING","Kommentar Posting");
define("_SENDTOFRIEND","An einen Freund senden");
define("_BROKENVIDS","Nicht funktionierende Videos");
define("_SUBMITVIDS","Videos Übertragen");
define("_RATING","Bewertung");
define("_ALLOWEDVIEW","Benutzer die die Videos sehen könnnen");
define("_SAVESETTINGS","Einstellungen Speichern");
define("_USERSCOMMENT","Benutzer die Kommentare zu den Videos abgeben dürfen");
define("_USEREMAIL","Benutzer die Videolinks in Emails verschicken dürfen");
define("_USERBROKEN","Benutzer die Videos als nicht funktionierend melden dürfen");
define("_USERSUBMIT","Benutzer die Videos übermitteln dürfen");
define("_USERMODERATE","Benutzer deren Videos überprüft werden müssen bevor sie in die Hauptvideosammlung übertragen werden");
define("_USERRATE","Benutzer die Videos bewerten dürfen");
define("_REQUESTSVIDS","Nachgefragte Videos");
define("_CATCOMFIRM","Sie sind dabei diese Kategorie zu löschen. Sind Sie sicher?");
define("_DELCAT","Kategorie Löschen");
define("_CATNAME","Kategoriebezeichnung");
define("_CATIMAGE","Kategoriebild url");
define("_ADDCAT","Kategorie Hinzufügen");
define("_ACCEPT","Aktzeptieren");
define("_REJECT","Ablehnen");
define("_NOVIDSRE","Es wurden keine Videos nachgefragt.");
define("_REQUESTA","Nachfrage Aktzeptiert");
define("_REQUESTD","Nachfrage Gelöscht");
define("_AREQUEST","Nachfrage Aktzeptieren");
define("_DREQUEST","Nachfrage Löschen");
define("_AREQUESTCOM","Sie sind dabei diese Nachfrage zu aktzeptieren. Sind Sie sicher?");
define("_DREQUESTCOM","Sie sind dabei diese Nachfrage zu löschen. Sind Sie sicher?"); 
// NEW TO V4.1 
define("_VIDSPERPAGE","Videos pro Seite"); 
define("_CHANGE","Ändern"); 
define("_EMBEDVIDURL","Video URL oder &lt;embed&gt; code"); 
define("_CUSTOMEMBED","Eigener &lt;embed&gt; Code"); 
// NEW TO V4.2
define("_DELETEENTRY","Eintrag löschen");
define("_PERMISSIONVIDS","Permission settings");
define("_MANAGECATEGORIES","Bearbeite Kategorien");
define("_PICTHUMB","Miniaturbild");
define("_COMFIRMCATDELETE","Sind Sie sich sicher, diese Kategorie zu löschen. Alle Videos in dieser Kategorie werden in die Default Kategorie verschoben.");
define("_DELCATNOTPARENT","Diese Kategorie ist eine Hauptkategorie, Bitte löschen Sie erst die untergeordneten Kategorien.");
define("_ERROR","Fehler!");
define("_ADDMAINCAT","Hauptkategorie hinzufügen");
define("_ADDSUBCAT","Unterkategorie hinzufügen");
define("_VS_IN","in");
define("_VS_AVCONTROL","Avatar Kontrolle");
define("_AVMAXWITHIE","Maximale Avatar Breite/Höhe");
define("_POINTSSYS","Punktesystem");
define("_VS_NAME","Name");
define("_VS_POINTS","Punkte");
define("_COMMENTPOINT","Kommentare");
define("_POINTSFORVIEW","Punkte");
define("_POINTSFORCOMMENT","Punkte, die für jedes abgegebene Kommentar eines Videos gegeben werden.");
define("_POINTSFORSENDTOFRIEND","Punkte, die für jeden versendeten Link eines Videos gegeben werden");
define("_POINTSFORSUBMITVIDEO","Punkte, die für jedes zugelassene Video gegeben werden");
define("_POINTSFORRATEVIDEO","Punkte, die für jede Bewertung eines Videos gegeben werden");
?>

