<?php
define("_ADMINMENU","Administration");
define("_VIDEOADMIN","Administration de Vidéo Stream");
define("_MANAGEVIDS","Gestion des vidéos");
define("_MANAGECATEG","Gestion des catégories");
define("_ADDVIDS","Ajouter des Vidéos");
define("_ADDVID","Ajouter une Vidéo");
define("_EDITVID","Editer la Video");
define("_VIDADDED","Vidéo Ajoutée");
define("_SETTINGSVIDS","Paramètres de Vidéo stream");
define("_TITLE","Titre");
define("_POSTEDON","Posté le ");
define("_POSTEDBY","Posté par");
define("_VVIEW","Voir");
define("_VIEWS","Vues");
define("_EDIT","Editer");
define("_DELETE","Supprimer");
define("_DELETEVID","Supprimer la Vidéo");
define("_PREVIOUS","Précédent");
define("_NEXT","Suivant");
define("_NOVIDSINDB","Vous n'avez encore ajouté aucune vidéo dans la base de données.");
define("_DESCRIPTION","Description");
define("_VIDURL","URL de la vidéo");
define("_PPURL","URL de la prévisualisation de l'image vidéo");
define("_WIDTH","Largeur");
define("_HEIGHT","Hauteur");
define("_PLUGIN","Plugins");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Besoin de ces champs");
define("_PAGE","Page");
define("_DELETEVIDCOMFIRM","Vous êtes sur le point de supprimer cette vidéo. Êtes-vous sûr?");
define("_YES","Oui");
define("_NO","Non");
define("_VIDDELETED","Vidéo supprimée");
define("_BACK","Retour");
define("_NONE","Aucune");
define("_CATEGORY","Catégorie");
define("_ENTDELETED","Entrée supprimée");
define("_ENTRYCOMFIRM","Vous êtes sûr le point de supprimer toutes les entrées pour cette vidéo. Êtes-vous sûr ?");
define("_REPORTEDBROKE","Les vidéos qui ont été rapportées ne fonctionnent pas ");
define("_VIDNAME","Nom de la vidéo");
define("_USERNAME","Pseudo");
define("_EMAIL","Email");
define("_DELETEENT","Supprimer toutes les entrées pour cette vidéo ");
define("_GO","Valider");
define("_GOBACKVID","Revenir au panneau d'administration de Vidéo Stream?");
define("_NOBROKEN","Aucune vidéo n'a été rapporté comme cassée");
define("_ENABLE","Activer");
define("_DISABLE","Désactiver");
define("_EVERYONE","Tout le monde");
define("_NOONE","Personne");
define("_VISONLY","Visiteurs seulement");
define("_REGMEMBERSONLY","Membres enregistrés seulement");
define("_COMMENTPOSTING","Commentaires des vidéos");
define("_SENDTOFRIEND","Envoyer à un ami");
define("_BROKENVIDS","Vidéos cassées");
define("_SUBMITVIDS","Soumettre une vidéo");
define("_RATING","Classement");
define("_ALLOWEDVIEW","Utilisateurs autorisés à regarder les vidéos");
define("_SAVESETTINGS","Enregistrer les paramètres");
define("_USERSCOMMENT","Utilisateurs autorisés à commenter les vidéos");
define("_USEREMAIL","Utilisateurs autorisés à envoyer des liens de vidéos dans les emails");
define("_USERBROKEN","Utilisateurs autorisés à rapporter les vidéos cassées");
define("_USERSUBMIT","utilisateurs autorisés à soumettre des vidéos");
define("_USERMODERATE","Utilisateurs dont les vidéos ont besoin d'être vérifiées pour être validées");
define("_USERRATE","Utilisateurs autorisés à voter pour les vidéos");
define("_REQUESTSVIDS","Requetes de Vidéos");
define("_CATCOMFIRM","Vous êtes sur le point de supprimer cette catégorie. Êtes-vous sûr?");
define("_DELCAT","Supprimer la catégorie");
define("_CATNAME","Nom de la catégorie");
define("_CATIMAGE","URL de l'image de la catégorie");
define("_ADDCAT","Ajouter une catégorie");
define("_ACCEPT","Accepter");
define("_REJECT","Refuser");
define("_NOVIDSRE","Aucune vidéo n'a fait l'objet d'une requete.");
define("_REQUESTA","Requete acceptée");
define("_REQUESTD","Requete supprimée");
define("_AREQUEST","Accepter la requete");
define("_DREQUEST","Supprimer la requete");
define("_AREQUESTCOM","Vous êtes sur le point d'accepter cette requete. Etes vous sûr?");
define("_DREQUESTCOM","Vous êtes sur le point de supprimer cette requete. Etes vous sûr?");
// NEW TO V4.1
define("_VIDSPERPAGE","Nombre de Vidéos par Page");
define("_CHANGE","Changer");
define("_EMBEDVIDURL","URL de la vidéo ou code &lt;embed&gt;");
define("_CUSTOMEMBED","Personnaliser Code &lt;embed&gt;");
?>
