<?php
define("_ADMINMENU","Adminisztráció");
define("_VIDEOADMIN","Videó Admin");
define("_MANAGEVIDS","Videók Kezelése");
define("_ADDVIDS","Videók Hozzáadása");
define("_ADDVID","Videó Hozzáadása");
define("_EDITVID","Videó Szerkesztése");
define("_VIDADDED","Videó Hozzáadva");
define("_SETTINGSVIDS","Videó Stream Beállítások");
define("_TITLE","Cím");
define("_POSTEDON","Beküldve");
define("_POSTEDBY","Beküldte");
define("_VVIEW","Megnéz");
define("_VIEWS","Megnézve");
define("_EDIT","Szerkesztés");
define("_DELETE","Törlés");
define("_DELETEVID","Videó Törlése");
define("_PREVIOUS","Elõzõ");
define("_NEXT","Következõ");
define("_NOVIDSINDB","Nem adtál még videót az adatbázishoz.");
define("_DESCRIPTION","Leírás");
define("_VIDURL","Videó URL");
define("_PPURL","Elõnézeti Kép URL");
define("_WIDTH","Szélesség");
define("_HEIGHT","Magasság");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Kötelezõ Mezõk (Kitölteni)");
define("_PAGE","Oldal");
define("_DELETEVIDCOMFIRM","A videó törlésére készülsz. Biztos ezt akarod?");
define("_YES","Igen");
define("_NO","Nem");
define("_VIDDELETED","Videó törölve");
define("_BACK","vissza");
define("_NONE","Semmi");
define("_CATEGORY","Kategória");
define("_ENTDELETED","Bejegyzás?Entry törölve");
define("_ENTRYCOMFIRM","A videó összes bejegyzésének törlésére készülsz. Biztos ezt akarod?");
define("_REPORTEDBROKE","Nem mûködõ Videóként jelzett");
define("_VIDNAME","Videó Neve");
define("_USERNAME","Felhasználó");
define("_EMAIL","Email");
define("_DELETEENT","A Videó összes bejegyzésének törlése");
define("_GO","Mehet");
define("_GOBACKVID","Vissza a Video Stream fõ admin menüjébe?");
define("_NOBROKEN","Nem jelentettek hibás vudeót");
define("_ENABLE","Bekapcsol");
define("_DISABLE","Kikapcsol");
define("_EVERYONE","Mindenki");
define("_NOONE","Senki");
define("_VISONLY","Csak Látogatók");
define("_REGMEMBERSONLY","Csak Regisztráét Felhasználók");
define("_COMMENTPOSTING","Hozzászólások Küldése");
define("_SENDTOFRIEND","Elküldés egy Ismerõsnek");
define("_BROKENVIDS","Hibás Videó");
define("_SUBMITVIDS","Videók Hozzáadása");
define("_RATING","Osztályzás");
define("_ALLOWEDVIEW","Videót megnézheti");
define("_SAVESETTINGS","Beállítások Mentése");
define("_USERSCOMMENT","Hozzászólást Küldhet");
define("_USEREMAIL","Videó linket küldhet emailben");
define("_USERBROKEN","Hibás Videót jelenthet");
define("_USERSUBMIT","Videót küldhet be");
define("_USERMODERATE","Videóit ellenõrizni kell, mielõtt kikerülne az oldalra");
define("_USERRATE","Videót osztályozhatja");
define("_REQUESTSVIDS","Kért Videó");
define("_CATCOMFIRM","A Kategória törlésére készülsz. Biztos ezt akarod?");
define("_DELCAT","Kategória Törlése");
define("_CATNAME","Kategória neve");
define("_CATIMAGE","Kategória kép url");
define("_ADDCAT","Kategória Hozzáadása");
define("_ACCEPT","Elfogad");
define("_REJECT","Elutasít");
define("_NOVIDSRE","Nem kértek videót.");
define("_REQUESTA","Kérés Elfogadva");
define("_REQUESTD","Kérés Visszautasítva");
define("_AREQUEST","Kérés Elfogadása");
define("_DREQUEST","Kérés Visszautasítása");
define("_AREQUESTCOM","A Kérés elfogadására készülsz. Biztos ezt akarod?");
define("_DREQUESTCOM","A Kérés visszautasítására készülsz. Biztos ezt akarod?");
// NEW TO V4.1
define("_VIDSPERPAGE","Videók oldalanként");
define("_CHANGE","Változtat");
define("_EMBEDVIDURL","Videó URL vagy &lt;embed&gt; code");
define("_CUSTOMEMBED","Egyéni &lt;embed&gt; Code");
?>