<?php
define("_ADMINMENU","Administración");
define("_VIDEOADMIN","Admin Video");
define("_MANAGEVIDS","Modificar Videos");
define("_ADDVIDS","Añade Videos");
define("_ADDVID","Añadir Vídeo");
define("_EDITVID","Editar Video");
define("_VIDADDED","Video Añadido");
define("_SETTINGSVIDS","Opciones de Stream");
define("_TITLE","Titulo");
define("_POSTEDON","Publicado el");
define("_POSTEDBY","Publicado por");
define("_VVIEW","Ver");
define("_VIEWS","Visto");
define("_EDIT","Editar");
define("_DELETE","Eleminar");
define("_DELETEVID","Eliminar Video");
define("_PREVIOUS","Anterior");
define("_NEXT","Siguiente");
define("_NOVIDSINDB","Todavía no has añadido ningun video.");
define("_DESCRIPTION","Descripción");
define("_VIDURL","URL del Video");
define("_PPURL","URL de foto vista previa");
define("_WIDTH","Ancho");
define("_HEIGHT","Alto");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Campos requeridos");
define("_PAGE","Pagina");
define("_DELETEVIDCOMFIRM","Vas a borrar este video. ¿Estas seguro?");
define("_YES","Si");
define("_NO","No");
define("_VIDDELETED","Video borrado");
define("_BACK","Atras");
define("_NONE","Nada");
define("_CATEGORY","Categoria");
define("_ENTDELETED","Entrada Borrada");
define("_ENTRYCOMFIRM","Vas a borrar todas las entradas de video. ¿Estas seguro?");
define("_REPORTEDBROKE","Avisos de videos que no funcionan");
define("_VIDNAME","Nombre del Video");
define("_USERNAME","Usuario");
define("_EMAIL","Email");
define("_DELETEENT","Borrar todas las entradas de este video");
define("_GO","Ir");
define("_GOBACKVID","¿Volver al menu de administración?");
define("_NOBROKEN","No hay avisos de videos rotos");
define("_ENABLE","Activar");
define("_DISABLE","Desactivar");
define("_EVERYONE","Publico");
define("_NOONE","Nadie");
define("_VISONLY","Visitantes solo");
define("_REGMEMBERSONLY","Usuarios registrados solo");
define("_COMMENTPOSTING","Enviar comentarios");
define("_SENDTOFRIEND","Enviar a un amigo");
define("_BROKENVIDS","Videos Rotos");
define("_SUBMITVIDS","Videos Enviados");
define("_RATING","Puntuación");
define("_ALLOWEDVIEW","Usuarios que pueden ver el video");
define("_SAVESETTINGS","Salvar configuración");
define("_USERSCOMMENT","Usuarios que pueden comentar el video");
define("_USEREMAIL","Usuarios que pueden recomendar por mail");
define("_USERBROKEN","Usuarios que pueden avisar de video roto");
define("_USERSUBMIT","Usuariso que pueden enviar videos");
define("_USERMODERATE","Usuarios que necesitan ser chequeados en sus envios de videos.");
define("_USERRATE","Usuarios que pueden valorar videos");
define("_REQUESTSVIDS","Videos Enviados");
define("_CATCOMFIRM","Vas a borrar esta categoria. ¿Estas seguro?");
define("_DELCAT","Eliminar Categoria");
define("_CATNAME","Nombre de la categoria");
define("_CATIMAGE","URL de la imagen de la categoria");
define("_ADDCAT","Añadir Categoria");
define("_ACCEPT","Aceptar");
define("_REJECT","Rechazar");
define("_NOVIDSRE","No hay videos enviados.");
define("_REQUESTA","Envio Aceptado");
define("_REQUESTD","Envio Borrado");
define("_AREQUEST","Acptar Envio");
define("_DREQUEST","Borrar Envio");
define("_AREQUESTCOM","Vas a aceptar este video ¿Estas seguro?");
define("_DREQUESTCOM","Vas a rechazar este envio ¿Estas seguro?");
// NEW TO V4.1
define("_VIDSPERPAGE","Videos por Pagina");
define("_CHANGE","Cambiar");
define("_EMBEDVIDURL","Video URL or &lt;embed&gt; Codidigo");
define("_CUSTOMEMBED","Custom &lt;embed&gt; Codidgo");
// NEW TO V4.2
define("_DELETEENTRY","Borrar Entrada");
define("_PERMISSIONVIDS","Elegir Permisos");
define("_MANAGECATEGORIES","Administrar Categorias");
define("_PICTHUMB","Thumbnail de la foto");
define("_COMFIRMCATDELETE","¿Estas seguro de que quieres eliminar esta categoria?. Cualquier video que haya en esta categoria será puesto en la categoria que viene por defecto.");
define("_DELCATNOTPARENT","Esta categoria es principal, porfavor elimina las subcategorias primero para proceder a eliminarla");
define("_ERROR","ERROR!");
define("_ADDMAINCAT","Añadir categoria principal");
define("_ADDSUBCAT","Añadir subcategoria");
define("_VS_IN","en");
define("_VS_AVCONTROL","Control de Avatares");
define("_AVMAXWITHIE","Maximo ancho/largo de avatar");
define("_POINTSSYS","Sistema de Puntos");
define("_VS_NAME","Nombre");
define("_VS_POINTS","Puntos");
define("_COMMENTPOINT","Comentar");
define("_POINTSFORVIEW","Puntos ganados cada vez que un usuario ve un video.");
define("_POINTSFORCOMMENT","Puntos ganados cada vez que un usuario comenta un video.");
define("_POINTSFORSENDTOFRIEND","Puntos ganados cada vez que un usuario envia el link a un amigo");
define("_POINTSFORSUBMITVIDEO","Puntos ganados por los usuarios que envian un video a la web.");
define("_POINTSFORRATEVIDEO","Puntos ganados por cada vez que un usuario valora un video.");
// NEW to 4.5
define("_YOUTUBEVP", "Reproductor YouTube");
define("_WINAMP", "Winamp"); 
define("_GOOGLEVP", "Reproductor Google");
define("_CATCANBEVIEWEDBY", "La categoría puede ser vista por");
define("_REQUIREUSERTOACCEPT", "Requiere que el usuario acepte las condiciones");
define("_EDITCAT", "Editar Categoría");
define("_DOWNLOADLINK", "Link de Descarga");
define("_UADOWNLOADLINK", "Usuarios a los que se les permite ver el link de descarga");
define("_EMBEDEDHTML", "Embeded HTML");
define("_UAEMBEDEDHTML", "Usuarios a los que se les permite ver el HTML embebido");
?>