<?php
define("_ADMINMENU","Adminastrie");
define("_VIDEOADMIN","Video Admin");
define("_MANAGEVIDS","Beheer Videos");
define("_ADDVIDS","Videos toevoegen");
define("_ADDVID","Video toevoegen");
define("_EDITVID","Video bewerken");
define("_VIDADDED","Video toegevoegd");
define("_SETTINGSVIDS","Video Stream Settings");
define("_TITLE","Titel");
define("_POSTEDON","gepost op");
define("_POSTEDBY","gepost door");
define("_VVIEW","View");
define("_VIEWS","Views");
define("_EDIT","Bewerken");
define("_DELETE","Verwijderen");
define("_DELETEVID","Video verwijderen");
define("_PREVIOUS","Vorige");
define("_NEXT","Volgende");
define("_NOVIDSINDB","Jij hebt nog geen videos in de database toegevoegd .");
define("_DESCRIPTION","Beschrijving");
define("_VIDURL","Video URL");
define("_PPURL","Picture voorvertoning URL");
define("_WIDTH","Breedte");
define("_HEIGHT","Hoogte");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Benodigde velden");
define("_PAGE","Pagina");
define("_DELETEVIDCOMFIRM","Weet je zeker dat je deze video wilt verwijderen?");
define("_YES","Ja");
define("_NO","Nee");
define("_VIDDELETED","Video verwijderd");
define("_BACK","terug");
define("_NONE","Geen");
define("_CATEGORY","Categorie");
define("_ENTDELETED","Entry verwijderd");
define("_ENTRYCOMFIRM","Weet je zeker dat je alle entries voor deze video wilt verwijderen?");
define("_REPORTEDBROKE","Videos aangegeven die niet werken");
define("_VIDNAME","Video Naam");
define("_USERNAME","Gebruikersnaam");
define("_EMAIL","Email");
define("_DELETEENT","Verwijder alle entries voor deze video");
define("_GO","Ga");
define("_GOBACKVID","Terug gaan naar Video Stream's main admin area?");
define("_NOBROKEN","geen videos zijn als fout opgegeven");
define("_ENABLE","Inschakelen");
define("_DISABLE","Uitschakelen");
define("_EVERYONE","Iedereen");
define("_NOONE","Niemand");
define("_VISONLY","Alleen bezoekers");
define("_REGMEMBERSONLY","Alleen geregristreerde leden");
define("_COMMENTPOSTING","Commentaar post");
define("_SENDTOFRIEND","Naar vriend versturen");
define("_BROKENVIDS","Foutieve videos");
define("_SUBMITVIDS","Videos toevoegen");
define("_RATING","Rating");
define("_ALLOWEDVIEW","gebruikers toegestaan om videos te kijken");
define("_SAVESETTINGS","Settings opslaan");
define("_USERSCOMMENT","gebruikers toegestaan om op videos te reageren");
define("_USEREMAIL","Gebruikers toegestaan om  een video link te sturen via mail");
define("_USERBROKEN","Gebruikers toegestaan om foutieve videos te melden");
define("_USERSUBMIT","Gebruikers toegestaan om videos toe te voegen");
define("_USERMODERATE","Gebruikers waarvan hun videos eerst moeten worden toegestaan");
define("_USERRATE","Gebruikers toegestaan om videos te beoordelen");
define("_REQUESTSVIDS","Verzochte videos");
define("_CATCOMFIRM","Weet je zeker dat je deze categorie wilt verwijderen?");
define("_DELCAT","Categorie verwijderen");
define("_CATNAME","Categorie naam");
define("_CATIMAGE","Categorie image url");
define("_ADDCAT","categorie toevoegen");
define("_ACCEPT","Accepteren");
define("_REJECT","Weigeren");
define("_NOVIDSRE","Er zijn geen videos verzocht.");
define("_REQUESTA","Verzoek geaccepteerd");
define("_REQUESTD","Verzoek afgewezen");
define("_AREQUEST","Verzoek accepteren");
define("_DREQUEST","Verzoek afwijzen");
define("_AREQUESTCOM","Weet je zeker dat je dit verzoek wilt accepteren?");
define("_DREQUESTCOM","Weet je zeker dat je dit verzoek wilt weigeren?");
// NEW TO V4.1 
define("_VIDSPERPAGE","Videos per Pagina"); 
define("_CHANGE","Veranderen"); 
define("_EMBEDVIDURL","Video URL or &lt;embed&gt; code"); 
define("_CUSTOMEMBED","Custom &lt;embed&gt; Code"); 
?>