<?php
define("_ADMINMENU","Administracija");
define("_VIDEOADMIN","Video Administrator");
define("_MANAGEVIDS","Uredi video fajlove");
define("_ADDVIDS","Dodaj više videa");
define("_ADDVID","Dodaj video");
define("_EDITVID","Uredi video");
define("_VIDADDED","Video dodan");
define("_SETTINGSVIDS","Video Stream podešavanja");
define("_TITLE","Naziv");
define("_POSTEDON","Dodan");
define("_POSTEDBY","Postavio");
define("_VVIEW","Pregleda");
define("_VIEWS","Pregleda");
define("_EDIT","Uredi");
define("_DELETE","Izbriši");
define("_DELETEVID","Izbriši video");
define("_PREVIOUS","Prethodna");
define("_NEXT","Naredna");
define("_NOVIDSINDB","Niste dodali nijedan video fajlu bazu.");
define("_DESCRIPTION","Opis");
define("_VIDURL","Video URL");
define("_PPURL","Slika iz videa URL");
define("_WIDTH","Širina");
define("_HEIGHT","Visina");
define("_PLUGIN","Plugin");
define("_WINDOWSMP","Windows Media Player");
define("_FLASHP","Flash Player");
define("_QUICKTIMEP","Quicktime Player");
define("_REALP","Real Player");
define("_REQUIRED","Obavezna polja");
define("_PAGE","Stranica");
define("_DELETEVIDCOMFIRM","Želite li stvarno izbrisati ovaj fajl?");
define("_YES","Da");
define("_NO","Ne");
define("_VIDDELETED","Video je izbrisan");
define("_BACK","nazad");
define("_NONE","Nema");
define("_CATEGORY","Kategorija");
define("_ENTDELETED","Unos izbrisan");
define("_ENTRYCOMFIRM","Želite li stvarno izbrisati sve unose za ovaj fajl?");
define("_REPORTEDBROKE","Video je prijavljen kao neispravan");
define("_VIDNAME","Naziv videa");
define("_USERNAME","Korisnik");
define("_EMAIL","E-mail");
define("_DELETEENT","Izbrišite sve unose za ovaj video");
define("_GO","Idi");
define("_GOBACKVID","Vratiti se na Video Stream osnovu admin stranicu?");
define("_NOBROKEN","Nema prijavljenih video fajlova");
define("_ENABLE","Omoguæi");
define("_DISABLE","Onemoguæi");
define("_EVERYONE","Svako");
define("_NOONE","Niko");
define("_VISONLY","Samo posjetitelji");
define("_REGMEMBERSONLY","Samo registrirani");
define("_COMMENTPOSTING","Postavljanje komentara");
define("_SENDTOFRIEND","Pošalji prijatelju");
define("_BROKENVIDS","Video s kvarom");
define("_SUBMITVIDS","Postavi video");
define("_RATING","Ocjena");
define("_ALLOWEDVIEW","Korisnici sa moguænošæu pregleda ovog video fajla");
define("_SAVESETTINGS","Snimi promjene");
define("_USERSCOMMENT","Korisnici sa moguænošæu komentiranja ovog video fajla");
define("_USEREMAIL","Korisnici sa moguænošæu slanja linka ovog video fajla putem e-maila");
define("_USERBROKEN","Korisnici sa moguænošæu prijave kvara na ovom video fajlu");
define("_USERSUBMIT","Korisnicima omoguæeno postavljanje video fajlova");
define("_USERMODERATE","Provjera video fajlova prije upisa u galeriju");
define("_USERRATE","Korisnici sa moguænošæu glasanja");
define("_REQUESTSVIDS","Zahtjevani video fajlovi");
define("_CATCOMFIRM","Stvarno želite izbrisati ovu kategoriju?");
define("_DELCAT","Izbriši kategoriju");
define("_CATNAME","Naziv kategorije");
define("_CATIMAGE","URL do slike za kategoriju");
define("_ADDCAT","Dodaj kategoriju");
define("_ACCEPT","Prihvati");
define("_REJECT","Odbaci");
define("_NOVIDSRE","Nema zahtjevanih video fajlova.");
define("_REQUESTA","zahtjev prihvaæen");
define("_REQUESTD","Zahtjev izbrisan");
define("_AREQUEST","Prihvati zahtjev");
define("_DREQUEST","Izbriši zahtjev");
define("_AREQUESTCOM","Želite li stvarno prihvatiti ovaj zahtjev?");
define("_DREQUESTCOM","Želite li stvarno izbrisati ovaj zahtjev?");
// NEW TO V4.1
define("_VIDSPERPAGE","Videa po stranici");
define("_CHANGE","Promijeni");
define("_EMBEDVIDURL","Video URL ili &lt;embed&gt; code");
define("_CUSTOMEMBED","Uredi code");
// NEW TO V4.2
define("_DELETEENTRY","Izbriši unos");
define("_PERMISSIONVIDS","Podešavanje dopuštenja");
define("_MANAGECATEGORIES","Baratanje kategorijama");
define("_PICTHUMB","Umanjena slika");
define("_COMFIRMCATDELETE","Ako izbrišete ovu kategoriju svi video fajlovi æe biti smješteni u osnovnu kategoriju.");
define("_DELCATNOTPARENT","Ovo je nadkategorija. Izbrišite prvo podkategorije");
define("_ERROR","GREŠKA!");
define("_ADDMAINCAT","Dodaj osnovnu kategoriju");
define("_ADDSUBCAT","Dodaj podkategoriju");
define("_VS_IN","u");
define("_VS_AVCONTROL","Kontrola avatara");
define("_AVMAXWITHIE","Maksimalna šir/vis. avatara");
define("_POINTSSYS","Sistem poentiranja");
define("_VS_NAME","Ime");
define("_VS_POINTS","Poena");
define("_COMMENTPOINT","Komentar");
define("_POINTSFORVIEW","Poeni se dodaju na svaki dodani video fajl");
define("_POINTSFORCOMMENT","Poeni se dodaju na svaki upisani komantar");
define("_POINTSFORSENDTOFRIEND","Poeni se dodaju na svako slanje linka prijatelju");
define("_POINTSFORSUBMITVIDEO","Poeni se dodaju na svako dodavanje videa u kolekciju");
define("_POINTSFORRATEVIDEO","Poeni se dodaju na svako komentiranje video fajla");
?>